#version: "3"
# The parser will ignore extension fields prefixed with x-
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 

include:
  #- path: ../mysql/mysql.yaml
  #  project_directory: ./mysql
  - path: ./proxy.yaml
    project_directory: .
     
services:
  db:
    image: mariadb:10.6.4-focal
    #"mysql_native_password" only for wordpress, usually don't need!
    #command: "--default-authentication-plugin=mysql_native_password"  # <--- При выполнени домашнего задания не использовать!!
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # <--- Это вам обязательно понадобится при выполнении ДЗ!

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
      #- DB_TABLE=${MYSQL_TABLE_NAME:-requests}
    depends_on: ["db", "ingress-proxy", "reverse-proxy"]
    #ports: ["80:80"]
    #networks: ["backend"]
    networks:
      backend:
        ipv4_address: 172.20.0.5

volumes:
  mariadb_data: {}

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24

